---
# Where things are fetched from
base_path: /home/jacopo/PycharmProjects/progetto-tesi/
# Subpath to where the dataset is places
data_path: resources/${dataset}/
# Subpath to where output has to go to.
output_path: data/${dataset}/extraction_data/
points_loader_classpath: main.dataset.${dataset}.loader
points_loader_classname: ${dataset}PointsLoader
# Strategy to divide in segments
segmenter_type: main.core_data.sampler.EegFeaturesAndRandLogUIntervalsSegmenter
segmenter_args:
  min_length: 4
  max_length: 32
  num_segments: 20
  anchor_identification_hop: 0.125
  extraction_jitter: 0.1
